name: Create CSV

on: workflow_dispatch

permissions:
  contents: write

jobs:
  create-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create CSV
        run: |
          echo "Test,Status" > report.csv
          echo "Login,PASS" >> report.csv
          echo "Signup,FAIL" >> report.csv

      - name: Push CSV to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add report.csv
          git commit -m "Add CSV report"
          git push
